# Welcome to Jekyll!
#

# Site settings
title: BFH Abogados
description: |
  Solamente aquel que  
  contribuye al futuro tiene  
  derecho a juzgar el pasado
owner: BFH Abogados # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: bfhabogados@telefonica.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bfhabogado.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
#sass:
#  style: compressed
